import js from '@eslint/js';
import tseslint from 'typescript-eslint';

/**
 * Dependency direction for the monorepo. A package may import ONLY the
 * packages listed for it. This is the machine-checked form of the rule in
 * CLAUDE.md; violating it is a lint error, not a code-review opinion.
 */
export const DEPENDENCY_GRAPH = {
  '@ft/contracts': [],
  '@ft/symbology': ['@ft/contracts'],
  '@ft/quant': ['@ft/contracts'],
  '@ft/ui': ['@ft/contracts'],
  '@ft/quant-worker': ['@ft/contracts', '@ft/quant'],
  '@ft/market-data': ['@ft/contracts', '@ft/symbology'],
  '@ft/db': ['@ft/contracts', '@ft/symbology'],
  '@ft/ai': ['@ft/contracts', '@ft/symbology', '@ft/quant', '@ft/market-data'],
  '@ft/alerts': ['@ft/contracts', '@ft/symbology', '@ft/quant', '@ft/market-data'],
  web: ['*'],
};

/**
 * Packages that must run unchanged in a Web Worker, a browser, and a
 * serverless function. They may not reach for a platform API.
 */
const PLATFORM_FREE = new Set(['@ft/contracts', '@ft/quant']);

function restrictedImports(pkg) {
  const allowed = DEPENDENCY_GRAPH[pkg] ?? [];
  const patterns = [];

  if (!allowed.includes('*')) {
    const forbidden = Object.keys(DEPENDENCY_GRAPH).filter(
      (p) => p !== pkg && p !== 'web' && !allowed.includes(p),
    );
    for (const dep of forbidden) {
      patterns.push({
        group: [dep, `${dep}/*`],
        message: `${pkg} may not import ${dep}. Allowed: ${allowed.join(', ') || '(nothing)'}. See CLAUDE.md § dependency direction.`,
      });
    }
  }

  if (PLATFORM_FREE.has(pkg)) {
    patterns.push({
      group: ['node:*', 'fs', 'path', 'crypto', 'http', 'https', 'os', 'child_process'],
      message: `${pkg} must stay platform-free — it runs in a Web Worker, a browser, and a serverless function. Move platform code to the package that owns the side effect.`,
    });
  }

  return patterns.length ? { 'no-restricted-imports': ['error', { patterns }] } : {};
}

/** @param {{ pkg: string, files?: string[] }} opts */
export function ftConfig({ pkg, files = ['src/**/*.ts', 'src/**/*.tsx'] }) {
  return tseslint.config(
    {
      ignores: [
        'dist/**',
        '.next/**',
        'node_modules/**',
        'coverage/**',
        '.turbo/**',
        // Generated by Next on every build; not ours to lint.
        'next-env.d.ts',
      ],
    },
    js.configs.recommended,
    ...tseslint.configs.recommended,
    {
      files,
      rules: {
        ...restrictedImports(pkg),
        '@typescript-eslint/consistent-type-imports': [
          'error',
          { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
        ],
        '@typescript-eslint/no-unused-vars': [
          'error',
          { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
        ],
        '@typescript-eslint/no-explicit-any': 'warn',
        eqeqeq: ['error', 'always', { null: 'ignore' }],
        'no-console': ['warn', { allow: ['warn', 'error'] }],
      },
    },
    {
      files: ['src/**/*.test.ts'],
      rules: { '@typescript-eslint/no-explicit-any': 'off', 'no-console': 'off' },
    },
  );
}

export default ftConfig;
